### ISSUE TITLE
Cannot install course from zip file (or from Github repo) on Ubuntu

### ISSUE THREAD

**Issue by adpi2** [scalacenter/course-management-tools#300]
```
cmtc install -s ~/Documents/scala3-migration-course-student.zip
ERROR - Failed to execute command.
  Unexpected error(requirement failed: Source file '/tmp/sbt_e372480a/scala3-migration-course' is a directory.)
  /home/piquerez/Documents/scala3-migration-course-student.zip may be corrupt
```

I debugged this a bit and it seems the problem is here:
https://github.com/scalacenter/course-management-tools/blob/7df68014718e7d9f8cfae35d4a08dc33776ed583/cmtc/src/main/scala/com/lunatech/cmt/client/command/Install.scala#L84C19-L84C59

On my OS (Ubuntu), it seems that `sbtio.move` assumes the path is a file, not a directory.

**Comment by eloots** [comment]
@adpi2 this was already reported in #297 with a suggested fix
